---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: src/views/index.md
  label: Home
  match: "**/*"
- type: document
  path: src/views/events.md
  label: Events
  match: "**/*"
- type: document
  path: src/views/about.md
  label: About - About
  match: "**/*"
- type: document
  path: src/views/pottery.md
  label: About - Pottery
  match: "**/*"
- type: document
  path: src/views/process.md
  label: About - Process
  match: "**/*"
- type: document
  path: src/views/contact.md
  label: Contact
  match: "**/*"
- type: heading
  label: Data
- type: document
  path: src/views/_data/global.json
  label: Global
  match: "**/*"
- type: document
  path: src/views/_data/showcase.json
  label: Collections
  match: "**/*"
- type: document
  path: src/views/_data/events.json
  label: Events
  match: "**/*"
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
