---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/views/_data
  label: Data
  create: none
  match: "**/*.json"
- type: heading
  label: Pages
- type: directory
  path: src/views
  label: Pages
  create: none
  match: "**/*.md"
- type: heading
  label: Data
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
