backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/images"
public_folder: "/images"

collections:
  - label: "pages"
    name: "Pages"
    files: 
      - label: "home"
        name: "home"
        file: "src/views/home.md"
        fields:
          - {label: "layout", name: "layout", widget: "hidden", default: "home-layout"}
          - {label: "title", name: "title", widget: "string", default: "Home"}
          - {label: "permalink", name: "permalink", widget: "string", default: "/index.html"}
          
          - label: "eleventyNavigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - {label: "key", name: "key", widget: "string", default: "Home"}
              - {label: "order", name: "order", widget: "number", default: "1"}
          
          - label: "notification"
            name: "notification"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string", default: "Online Shopping is now available"}
              - {label: "subtitle", name: "subtitle", widget: "string", default: "Right to your front door! Free local delivery for orders over $150."}
              - label: "cta"
                name: "cta"
                widget: "object"
                collapsed: false
                fields: 
                  - {label: "label", name: "label", widget: "string", default: "Shop Now"}
                  - {label: "url", name: "url", widget: "string", default: "https://matthew-freed-pottery.myshopify.com/collections/all/1"}
          
          - label: "event"
            name: "event"
            widget: "object"
            collapsed: false
            fields:
              - label: "no_events"
                name: "no_events"
                widget: "object"
                collapsed: false
                fields:
                  - {label: "title", name: "title", widget: "text", default: "Kitsilano Farmer's Market. Sunday May 2nd from 9:30 am to 2:30 pm"}
                  - {label: "text", name: "text", widget: "text", default: "Watch out for <a href=\"/updates\">updates</a>. I'll keep you posted!"}
              - label: "image"
                name: "image"
                widget: "object"
                collapsed: false
                fields:
                  - {label: "url", name: "url", widget: "image", default: "/images/carousel-yaletown.jpg"}
                  - {label: "alt", name: "alt", widget: "string", default: "Yaletown Collection in the wild"}
              - {label: "title", name: "title", widget: "string", default: "Upcoming Events"}
              - {label: "label", name: "label", widget: "string", default: "Details"}
          
          - label: "gallery"
            name: "gallery"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string", default: "Explore my different glazing lines and pottery forms"}
              - label: "texts"
                name: "texts"
                widget: "list"
                allow_add: true
                default: ["Each piece is a complexity of nature, science, and art.", "Browse through my different collections and choose between a large variety of different glazes and forms. If you can't find what you are looking for, send me a message and we can talk about custom pieces."]
          
          - label: "features"
            name: "features"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string", default: "Featured Items"}
              - label: "texts"
                name: "texts"
                widget: "list"
                allow_add: true
                default: ["Handcrafted pottery. Are you looking for that one of a kind coffee mug?", "I'll be right there! Free delivery to your front door for orders over $150 (within 30 km)"]

          - {label: "custom_seo_settings", name: "custom_seo_settings", widget: "boolean", default: true}
          - {label: "author", name: "author", widget: "boolean", default: ''}
          - {label: "excerpt", name: "excerpt", widget: "string", default: ''}
          - {label: "image", name: "image", widget: "image", default: ''}
          - {label: "ogtype", name: "ogtype", widget: "string", default: ''}
