backend:
  name: git-gateway
  branch: decap

media_folder: "src/images"
public_folder: "/images"

collections:
  - label: "pages"
    name: "Pages"
    files: 
      - label: "contact"
        name: "contact"
        file: "src/views/contact.md"
        fields: 
          - {label: "layout", name: "layout", widget: "hidden"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "permalink", name: "permalink", widget: "string"}

          - label: "notification"
            name: "notification"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "subtitle", name: "subtitle", widget: "string"}
              - label: "cta"
                name: "cta"
                widget: "object"
                collapsed: false
                fields: 
                  - {label: "label", name: "label", widget: "string"}
                  - {label: "url", name: "url", widget: "string"}

          - {label: "headline", name: "headline", widget: "string"}
          - {label: "subheadline", name: "subheadline", widget: "string"}

          - label: "intro"
            name: "intro"
            widget: "list"
            fields:
              - {label: "text", name: "text", widget: "string"}

           - {label: "message", name: "message", widget: "string"}
           - {label: "phone", name: "phone", widget: "string"}
           - {label: "address", name: "address", widget: "string"}
           - {label: "gmaps", name: "gmaps", widget: "string"}


          - label: "eleventyNavigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - {label: "key", name: "key", widget: "string"}
              - {label: "order", name: "order", widget: "number"}

          - {label: "custom_seo_settings", name: "custom_seo_settings", widget: "boolean"}
          - {label: "author", name: "author", widget: "boolean", required: false}
          - {label: "excerpt", name: "excerpt", widget: "string", required: false}
          - {label: "image", name: "image", widget: "image", required: false}
          - {label: "ogtype", name: "ogtype", widget: "string", required: false}

      - label: "about"
        name: "about"
        file: "src/views/about.md"
        fields:
          - {label: "layout", name: "layout", widget: "hidden"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "permalink", name: "permalink", widget: "string"}

          - {label: "headline", name: "headline", widget: "string"}
          - {label: "intro", name: "intro", widget: "text"}

          - label: "sections"
            name: "sections"
            widget: "list"
            fields:
              - label: "image"
                name: "image"
                widget: "object"
                collapsed: false
                fields:
                  - {label: "url", name: "url", widget: "image"}
                  - {label: "alt", name: "alt", widget: "string"}
              - label: "paragraphs"
                name: "paragraphs"
                widget: "list"
                fields: 
                  - {label: "text", name: "text", widget: "string"}
              - {label: "label", name: "label", widget: "string"}

          - label: "eleventyNavigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - {label: "key", name: "key", widget: "string"}
              - {label: "order", name: "order", widget: "number"}

          - {label: "custom_seo_settings", name: "custom_seo_settings", widget: "boolean"}
          - {label: "author", name: "author", widget: "boolean", required: false}
          - {label: "excerpt", name: "excerpt", widget: "string", required: false}
          - {label: "image", name: "image", widget: "image", required: false}
          - {label: "ogtype", name: "ogtype", widget: "string", required: false}

      - label: "home"
        name: "home"
        file: "src/views/home.md"
        fields:
          - {label: "layout", name: "layout", widget: "hidden"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "permalink", name: "permalink", widget: "string"}

          - label: "notification"
            name: "notification"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "subtitle", name: "subtitle", widget: "string"}
              - label: "cta"
                name: "cta"
                widget: "object"
                collapsed: false
                fields: 
                  - {label: "label", name: "label", widget: "string"}
                  - {label: "url", name: "url", widget: "string"}
          
          - label: "event"
            name: "event"
            widget: "object"
            collapsed: false
            fields:
              - label: "no_events"
                name: "no_events"
                widget: "object"
                collapsed: false
                fields:
                  - {label: "title", name: "title", widget: "string"}
                  - {label: "text", name: "text", widget: "string"}
              - label: "image"
                name: "image"
                widget: "object"
                collapsed: false
                fields:
                  - {label: "url", name: "url", widget: "image"}
                  - {label: "alt", name: "alt", widget: "string"}
              - {label: "title", name: "title", widget: "string"}
              - {label: "label", name: "label", widget: "string"}
          
          - label: "gallery"
            name: "gallery"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string"}
              - label: "texts"
                name: "texts"
                widget: "list"
                fields: 
                  - {label: "text", name: "text", widget: "string"}

          - label: "features"
            name: "features"
            widget: "object"
            collapsed: false
            fields:
              - {label: "title", name: "title", widget: "string"}
              - label: "texts"
                name: "texts"
                widget: "list"
                fields: 
                  - {label: "text", name: "text", widget: "string"}

          - label: "eleventyNavigation"
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - {label: "key", name: "key", widget: "string"}
              - {label: "order", name: "order", widget: "number"}

          - {label: "custom_seo_settings", name: "custom_seo_settings", widget: "boolean"}
          - {label: "author", name: "author", widget: "boolean", required: false}
          - {label: "excerpt", name: "excerpt", widget: "string", required: false}
          - {label: "image", name: "image", widget: "image", required: false}
          - {label: "ogtype", name: "ogtype", widget: "string", required: false}
